
export const GUIA_REMISION_COLS = {
    CODIGO: 'codGuiaRemision',
    CODIGO_EMPRESA: 'codEmpresa',
    CODIGO_ALMACEN: 'codAlmacen',
    CODIGO_SUCURSAL: 'codSucursal',
    TIPO_DOCUMENTO: 'tipoDocumento',
    CLIENTE: 'cliente',
    SERIE: 'serieDocumento',
    NUMERO_DOCUMENTO: 'numeroDocumento',
    NUMERO_GUIA: 'numeroGuia',
    TRANSPORTISTA: 'transportistaNombre',
    CONDUCTOR: 'conductorNombre',
    LICENCIA_CONDUCTOR: 'licenciaConductor',
    PLACA_VEHICULO: 'vehiculoPlaca',
    ENTREGA_DESTINO: 'entregaEnDestino',
    UBIGEO_ORIGEN: 'ubigeoOrigen',
    DIRECCION_ORIGEN: 'direccionOrigen',
    REFERENCIAS_DESTINO: 'referenciasDestino',
    SOLICITANTE: 'solicitante',
    RECEPCIONISTA:'recepcionista',
    FECHA_EMISION: 'fechaEmision',
    COMPLETO: 'completo',
    USUARIO: 'usuario',
    FECHA_HORA: 'fecha',
    ANULADO: 'anulado',
    USUARIO_ANULACION: 'usuarioAnulacion',
    FECHA_ANULACION: 'fechaAnulacion',
    CODIGO_VENTA: 'codVenta',
    IGV_VENTA: 'igvVenta',
    IMPORTE_VENTA: 'importeVenta',
    DOCUMENTO_VENTA: 'documentoVenta',
    NRO_DOCUMENTO_VENTA: 'nroDocumentoVenta'
  };

  export const GUIA_REMISION_DETALLE_COLS = {
    CODIGO: 'codGuiaRemisionDetalle',
    CODIGO_EMPRESA: 'codEmpresa',
    CODIGO_ALMACEN: 'codAlmacen',
    CODIGO_SUCURSAL: 'codSucursal',
    CODIGO_GUIA: 'codGuiaRemision',
    ITEM: 'item',
    CODIGO_PRODUCTO: 'codProducto',
    CODIGO_PRODUCTO_ATR: 'codProductoAtributo',
    PRODUCTO: 'producto',
    CODIGO_UNIDAD: 'codUnidad',
    UNIDAD: 'unidad',
    CANTIDAD_VENDIDA: 'cantidadVendida',
    CANTIDAD_ENTREGADA: 'cantidadEntregada',
    CANTIDAD_ENTREGAR: 'cantidadEntregar',
    SUBTOTAL: 'subtotal',
    USUARIO: 'usuario',
    FECHA_HORA: 'fecha',
    ESTADO: 'estado',
    COMENTARIO: 'comentario'
  };